import React, { useEffect, useMemo, useState } from "react";
import { Routes, Route, useNavigate, useParams, useLocation } from "react-router-dom";
import { FaArrowLeft, FaArrowRight, FaFileAlt, FaMagic, FaSearch, FaStar, FaRegStar, FaEllipsisV, FaCheckCircle, FaSave, FaHistory, FaDownload, FaPrint } from "react-icons/fa";
import { draftsAPI, casesAPI, filesAPI, handleApiError } from "../../services/api";
import "./LegalDraftingPage.css";

const CATEGORIES = [
  ["civil", "Civil"], ["criminal", "Criminal"], ["family", "Family"], ["property", "Property"],
  ["corporate", "Corporate / Commercial"], ["constitutional", "Constitutional"], ["employment", "Employment"],
  ["banking_finance", "Banking / Finance"], ["tax", "Tax"], ["consumer", "Consumer"],
  ["intellectual_property", "Intellectual Property"], ["legal_notice", "Legal Notices"], ["application", "Applications"], ["agreement", "Agreements / Contracts"],
];

const BackTitle = ({ title, subtitle, children }) => {
  const navigate = useNavigate();
  return <header className="draft-page-header"><button className="draft-back" onClick={() => navigate(-1)} aria-label="Go back"><FaArrowLeft /></button><div><h1>{title}</h1>{subtitle && <p>{subtitle}</p>}</div>{children && <div className="draft-header-action">{children}</div>}</header>;
};

function DraftingHome() {
  const navigate = useNavigate(); const location = useLocation();
  const [tab, setTab] = useState(location.state?.caseId ? "create" : "drafts");
  const [drafts, setDrafts] = useState([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true);
  const load = async () => { try { const r = await draftsAPI.getAll({ search: query || undefined, limit: 100 }); setDrafts(r.data?.data || r.data?.drafts || []); } catch { setDrafts([]); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [query]);
  const favourites = drafts.filter((draft) => draft.isFavorite);
  return <main className="drafting-shell">
    <section className="drafting-intro"><div><span className="drafting-kicker">VOICE OF LAW</span><h1>Legal Drafting</h1><p>Create Pakistan-focused legal documents with your approved templates, case data and AI.</p></div><button className="draft-primary" onClick={() => setTab("create")}><FaMagic /> Create draft</button></section>
    <nav className="draft-tabs" aria-label="Drafting sections"><button className={tab === "drafts" ? "active" : ""} onClick={() => setTab("drafts")}>My Drafts</button><button className={tab === "templates" ? "active" : ""} onClick={() => { setTab("templates"); navigate("templates"); }}>Templates</button><button className={tab === "favorites" ? "active" : ""} onClick={() => setTab("favorites")}>Favorites</button></nav>
    {tab === "create" && <CreateMethod onTemplates={() => navigate("templates")} onAI={() => navigate("ai")} caseId={location.state?.caseId} onCase={() => navigate("case")} />}
    {(tab === "drafts" || tab === "favorites") && <DraftList drafts={tab === "favorites" ? favourites : drafts} loading={loading} query={query} setQuery={setQuery} onOpen={(id) => navigate(`drafts/${id}/edit`)} reload={load} />}
  </main>;
}

function CreateMethod({ onTemplates, onAI, onCase, caseId }) {
  return <section className="draft-methods"><div className="draft-section-copy"><h2>How would you like to create it?</h2><p>Choose a guided option. Blank documents are intentionally not included so every draft starts with structure and context.</p></div><button className="draft-choice" onClick={onTemplates}><FaFileAlt /><span><strong>Use a legal template</strong><small>Choose a court-ready template, then answer its questions.</small></span><FaArrowRight /></button><button className="draft-choice" onClick={onCase}><FaFileAlt /><span><strong>{caseId ? "Continue with this case" : "Create from a case"}</strong><small>Use existing client, court and case data without typing it again.</small></span><FaArrowRight /></button><button className="draft-choice" onClick={onAI}><FaMagic /><span><strong>Generate with AI</strong><small>Give facts and let the legal assistant prepare the first draft.</small></span><FaArrowRight /></button></section>;
}

function TemplateList() {
  const navigate = useNavigate(); const [templates, setTemplates] = useState([]); const [category, setCategory] = useState(""); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { let mounted = true; draftsAPI.listTemplates({ category: category || undefined }).then((r) => { if (mounted) setTemplates(r.data?.templates || r.data?.data?.templates || []); }).catch(() => mounted && setTemplates([])).finally(() => mounted && setLoading(false)); return () => { mounted = false; }; }, [category]);
  const visible = templates.filter((item) => `${item.name} ${item.description}`.toLowerCase().includes(search.toLowerCase()));
  return <main className="drafting-shell draft-narrow"><BackTitle title="Legal templates" subtitle="Select a Pakistan-focused template to begin." /><div className="draft-search"><FaSearch /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search templates" /></div><div className="draft-category-scroll"><button className={!category ? "active" : ""} onClick={() => setCategory("")}>All</button>{CATEGORIES.map(([value, label]) => <button key={value} className={category === value ? "active" : ""} onClick={() => setCategory(value)}>{label}</button>)}</div><div className="draft-template-list">{loading ? <p className="draft-muted">Loading templates…</p> : visible.length ? visible.map((template) => <button key={template._id} className="draft-template-row" onClick={() => navigate(`${template._id}`)}><FaFileAlt /><span><strong>{template.name}</strong><small>{template.documentType || template.category} · {template.province || "Pakistan"} · {template.language === "ur" ? "Urdu" : "English"}</small><em>{template.description}</em></span><FaArrowRight /></button>) : <div className="draft-empty"><FaFileAlt /><h2>No template available yet</h2><p>Templates are managed from the Admin Panel and will appear here for all users once enabled.</p></div>}</div></main>;
}

function TemplateDetail() {
  const { templateId } = useParams(); const navigate = useNavigate(); const [template, setTemplate] = useState(null); const [loading, setLoading] = useState(true);
  useEffect(() => { draftsAPI.getTemplate(templateId).then((r) => setTemplate(r.data?.template || r.data?.data?.template)).finally(() => setLoading(false)); }, [templateId]);
  if (loading) return <main className="drafting-shell draft-narrow"><BackTitle title="Template" /><p className="draft-muted">Loading template…</p></main>;
  if (!template) return <main className="drafting-shell draft-narrow"><BackTitle title="Template not found" /></main>;
  const preview = template.previewText || String(template.content || "").replace(/<[^>]*>/g, " ").slice(0, 1400);
  return <main className="drafting-shell draft-narrow"><BackTitle title={template.name} subtitle={`${template.documentType || template.category} · ${template.language === "ur" ? "Urdu" : "English"}`} /><article className="draft-template-hero"><p>{template.description || "A structured legal template for your drafting workflow."}</p><dl><div><dt>Province</dt><dd>{template.province || "Applicable Pakistan-wide"}</dd></div><div><dt>Court / jurisdiction</dt><dd>{template.court || template.jurisdiction || "Select while drafting"}</dd></div></dl><button className="draft-primary draft-full" onClick={() => navigate("questions")}>Create document <FaArrowRight /></button><div className="draft-trust"><span><FaCheckCircle /> Guided questions</span><span><FaCheckCircle /> Editable PDF & Word</span><span><FaCheckCircle /> Auto-save</span></div></article><section className="draft-preview-section"><h2>Template preview</h2><div className={`draft-paper ${template.language === "ur" ? "rtl" : ""}`}>{preview || "A preview will be added by the template administrator."}</div></section><section className="draft-detail-copy"><h2>About this document</h2><p>This template asks only for the details needed to prepare this document. You can review and edit every word before exporting.</p>{template.legalReferences?.length > 0 && <><h3>Template references</h3><ul>{template.legalReferences.map((item, index) => <li key={index}>{item.title}{item.citation ? ` — ${item.citation}` : ""}</li>)}</ul></>}</section></main>;
}

function DraftQuestions() {
  const { templateId } = useParams(); const navigate = useNavigate(); const [template, setTemplate] = useState(null); const [values, setValues] = useState({}); const [step, setStep] = useState(1); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { draftsAPI.getTemplate(templateId).then((r) => { const t = r.data?.template || r.data?.data?.template; setTemplate(t); setValues(Object.fromEntries((t?.requiredFields || []).map((field) => [field.key, ""]))); }); }, [templateId]);
  if (!template) return <main className="drafting-shell draft-narrow"><BackTitle title="Preparing questions" /></main>;
  const allFields = template.requiredFields || []; const steps = [...new Set(allFields.map((field) => field.step || 1))].sort((a, b) => a - b); const fields = allFields.filter((field) => (field.step || 1) === step); const finalStep = step === steps.at(-1);
  const update = (key, value) => setValues((previous) => ({ ...previous, [key]: value }));
  const next = async () => { const missing = fields.find((field) => field.required && !String(values[field.key] || "").trim()); if (missing) return setError(`${missing.label} is required.`); setError(""); if (!finalStep) return setStep(steps[steps.indexOf(step) + 1]); setSaving(true); try { const result = await draftsAPI.generate({ templateId, variables: values, title: values.documentTitle || `${template.name} draft` }); const draft = result.data?.draft || result.data?.data?.draft; if (draft?._id) navigate(`/user-panel/drafting/drafts/${draft._id}/edit`); else setError(result.data?.message || "Please complete the missing information."); } catch (err) { setError(handleApiError(err)); } finally { setSaving(false); } };
  return <main className="drafting-shell draft-narrow"><BackTitle title={template.name} subtitle={`Step ${steps.indexOf(step) + 1} of ${steps.length}`} /><div className="draft-progress"><span style={{ width: `${((steps.indexOf(step) + 1) / steps.length) * 100}%` }} /></div><section className="draft-question-section"><h2>{step === 1 ? "Document details" : "Additional information"}</h2><p>Save progress happens once your document is created. Required details are marked.</p>{error && <p className="draft-error">{error}</p>}{fields.map((field) => <Field key={field.key} field={field} value={values[field.key]} onChange={update} />)}</section><footer className="draft-wizard-footer"><button className="draft-text-button" onClick={() => step === steps[0] ? navigate(-1) : setStep(steps[steps.indexOf(step) - 1])}><FaArrowLeft /> Back</button><button className="draft-primary" disabled={saving} onClick={next}>{saving ? "Creating…" : finalStep ? "Create document" : "Next"} {!saving && <FaArrowRight />}</button></footer></main>;
}

function Field({ field, value, onChange }) { const common = { value: value || "", onChange: (e) => onChange(field.key, e.target.value), placeholder: field.helpText || `Enter ${field.label.toLowerCase()}` }; return <label className="draft-field"><span>{field.label}{field.required && <b> *</b>}</span>{field.type === "textarea" ? <textarea rows="5" {...common} /> : field.type === "select" ? <select {...common}><option value="">Select an option</option>{(field.options || []).map((option) => <option key={option} value={option}>{option}</option>)}</select> : field.type === "boolean" ? <select {...common}><option value="">Select</option><option value="yes">Yes</option><option value="no">No</option></select> : <input type={field.type || "text"} {...common} />}</label>; }

function DraftList({ drafts, loading, query, setQuery, onOpen, reload }) { const [openId, setOpenId] = useState(null); const action = async (event, draft, type) => { event.stopPropagation(); try { if (type === "favorite") await draftsAPI.toggleFavorite(draft._id); if (type === "delete" && window.confirm(`Delete “${draft.title}”?`)) await draftsAPI.delete(draft._id); await reload(); } catch (err) { window.alert(handleApiError(err)); } finally { setOpenId(null); } }; return <section className="draft-list-section"><div className="draft-list-tools"><div className="draft-search"><FaSearch /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search your drafts" /></div></div>{loading ? <p className="draft-muted">Loading drafts…</p> : drafts.length ? <div className="draft-record-list">{drafts.map((draft) => <article className="draft-record" key={draft._id} onClick={() => onOpen(draft._id)}><FaFileAlt /><div><h2>{draft.title}</h2><p>{draft.draftType} · {draft.status.replace("_", " ")} · Updated {new Date(draft.updatedAt).toLocaleDateString()}</p></div><button className="draft-star" onClick={(e) => action(e, draft, "favorite")} aria-label="Toggle favourite">{draft.isFavorite ? <FaStar /> : <FaRegStar />}</button><button className="draft-menu-button" onClick={(e) => { e.stopPropagation(); setOpenId(openId === draft._id ? null : draft._id); }} aria-label="Draft actions"><FaEllipsisV /></button>{openId === draft._id && <div className="draft-menu"><button onClick={() => onOpen(draft._id)}>Open</button><button onClick={(e) => action(e, draft, "favorite")}>{draft.isFavorite ? "Remove favourite" : "Add to favourites"}</button><button className="danger" onClick={(e) => action(e, draft, "delete")}>Delete</button></div>}</article>)}</div> : <div className="draft-empty"><FaFileAlt /><h2>No drafts yet</h2><p>Create a document from a template, case or AI guidance.</p></div>}</section>; }

function DraftEditor() { const { draftId } = useParams(); const navigate = useNavigate(); const [draft, setDraft] = useState(null); const [content, setContent] = useState(""); const [status, setStatus] = useState("Loading…"); const [versions, setVersions] = useState([]); const [showVersions, setShowVersions] = useState(false);
  useEffect(() => { draftsAPI.getById(draftId).then((r) => { const doc = r.data?.draft || r.data?.data?.draft; setDraft(doc); setContent(doc?.content || ""); setStatus("Saved"); }); }, [draftId]);
  useEffect(() => { if (!draft || content === draft.content) return; setStatus("Saving…"); const timer = setTimeout(async () => { try { const result = await draftsAPI.update(draftId, { content }); const changed = result.data?.draft || result.data?.data?.draft; setDraft(changed); setStatus("Saved"); } catch { setStatus("Could not save. Check connection."); } }, 1200); return () => clearTimeout(timer); }, [content, draft, draftId]);
  const exportDraft = async (format) => { try { const r = await draftsAPI.export(draftId, format); const url = r.data?.fileUrl || r.data?.data?.fileUrl; if (url) window.open(filesAPI.getFileUrl(url), "_blank", "noopener"); } catch (err) { window.alert(handleApiError(err)); } };
  const openVersions = async () => { const r = await draftsAPI.listVersions(draftId); setVersions(r.data?.versions || r.data?.data?.versions || []); setShowVersions(true); };
  const restore = async (version) => { if (!window.confirm("Restore this saved version? Your current content will first be saved as a new version.")) return; const r = await draftsAPI.restoreVersion(draftId, version._id); const doc = r.data?.draft || r.data?.data?.draft; setDraft(doc); setContent(doc.content); setShowVersions(false); };
  if (!draft) return <main className="drafting-shell draft-editor-shell"><BackTitle title="Opening document" /></main>;
  return <main className="drafting-shell draft-editor-shell"><BackTitle title={draft.title} subtitle={`${status} · ${draft.language === "ur" ? "Urdu" : "English"}`}><button className="draft-icon-action" onClick={openVersions} title="Version history"><FaHistory /></button><button className="draft-icon-action" onClick={() => exportDraft("pdf")} title="Download PDF"><FaDownload /></button></BackTitle><div className="draft-editor-toolbar"><button onClick={() => document.execCommand("bold")}>B</button><button onClick={() => document.execCommand("italic")}><i>I</i></button><button onClick={() => document.execCommand("insertUnorderedList")}>• List</button><button onClick={() => document.execCommand("insertOrderedList")}>1. List</button><button onClick={() => window.print()}><FaPrint /> Print</button><button onClick={() => draftsAPI.update(draftId, { content, createVersion: true, versionLabel: "Manual checkpoint" }).then((r) => { const updated = r.data?.draft || r.data?.data?.draft; setDraft(updated); setStatus("Version saved"); })}><FaSave /> Save version</button></div><div className={`draft-editor-paper ${draft.language === "ur" ? "rtl" : ""}`} contentEditable suppressContentEditableWarning onInput={(event) => setContent(event.currentTarget.innerHTML)} dangerouslySetInnerHTML={{ __html: content }} />{showVersions && <aside className="draft-version-panel"><div><h2>Version history</h2><button onClick={() => setShowVersions(false)}>×</button></div>{versions.length ? versions.slice().reverse().map((version) => <article key={version._id}><strong>{version.label || "Saved version"}</strong><small>{new Date(version.createdAt).toLocaleString()}</small><button onClick={() => restore(version)}>Restore</button></article>) : <p>No saved versions yet.</p>}</aside>}</main>;
}

function AiDraft() { const navigate = useNavigate(); const location = useLocation(); const caseId = location.state?.caseId; const [data, setData] = useState({ title: location.state?.caseTitle ? `${location.state.caseTitle} draft` : "", draftType: "legal_notice", facts: "", province: "", court: "", language: "en", caseId }); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const update = (key, value) => setData((old) => ({ ...old, [key]: value })); const generate = async () => { setLoading(true); setError(""); try { const r = await draftsAPI.generateAi(data); const draft = r.data?.draft || r.data?.data?.draft; navigate(`/user-panel/drafting/drafts/${draft._id}/edit`); } catch (err) { setError(handleApiError(err)); } finally { setLoading(false); } }; return <main className="drafting-shell draft-narrow"><BackTitle title="AI-guided draft" subtitle={caseId ? "This draft will also use the selected case information." : "Provide verified facts. The AI will mark missing information instead of inventing it."} /><section className="draft-question-section"><Field field={{ key:"title", label:"Document title", required:true }} value={data.title} onChange={update}/><label className="draft-field"><span>Document type *</span><select value={data.draftType} onChange={(e) => update("draftType", e.target.value)}>{CATEGORIES.map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="draft-field"><span>Language</span><select value={data.language} onChange={(e) => update("language", e.target.value)}><option value="en">English</option><option value="ur">Urdu</option></select></label><Field field={{key:"province",label:"Province",helpText:"e.g. Punjab"}} value={data.province} onChange={update}/><Field field={{key:"court",label:"Court / jurisdiction",helpText:"e.g. Lahore High Court"}} value={data.court} onChange={update}/><Field field={{key:"facts",label:"Verified facts and instructions",type:"textarea",required:true,helpText:"Include only facts you want used in the draft."}} value={data.facts} onChange={update}/>{error && <p className="draft-error">{error}</p>}<button className="draft-primary draft-full" disabled={loading} onClick={generate}>{loading ? "Generating…" : "Generate draft"} <FaMagic /></button></section></main>; }

function CasePicker() { const navigate = useNavigate(); const [items,setItems]=useState([]); useEffect(()=>{casesAPI.getAll({limit:100}).then(r=>setItems(r.data?.data||r.data?.cases||[]));},[]); return <main className="drafting-shell draft-narrow"><BackTitle title="Choose a case" subtitle="The selected case details will be used to guide your AI draft."/><div className="draft-template-list">{items.map(item=><button className="draft-template-row" key={item._id} onClick={()=>navigate("/user-panel/drafting/ai",{state:{caseId:item._id,caseTitle:item.title}})}><FaFileAlt/><span><strong>{item.title}</strong><small>{item.caseNo} · {item.court?.name}</small></span><FaArrowRight/></button>)}{!items.length&&<p className="draft-muted">No saved cases available.</p>}</div></main>; }

export default function LegalDraftingPage() { return <Routes><Route index element={<DraftingHome/>}/><Route path="templates" element={<TemplateList/>}/><Route path="templates/:templateId" element={<TemplateDetail/>}/><Route path="templates/:templateId/questions" element={<DraftQuestions/>}/><Route path="drafts/:draftId/edit" element={<DraftEditor/>}/><Route path="ai" element={<AiDraft/>}/><Route path="case" element={<CasePicker/>}/></Routes>; }
